sudo: required

branches:
 - unidata_17.1.1

language: ruby

env:
  matrix:
  - OS_VERSION=el6
  - OS_VERSION=el7

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull unidata/awips-ade:${OS_VERSION}

#script: build/setup.sh ${OS_VERSION} buildEDEX
